version = 0.1

[default.deploy.parameters]
stack_name = "genai-campaign-lg"
resolve_s3 = true
s3_prefix = "genai-campaign-lg"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true


[default.global.parameters]
region = "us-west-2"
