#!/bin/bash

# Setup Environment Variables Script
# This script extracts values from CloudFormation and creates .env file

set -e

# Get stack name from argument or use default
STACK_NAME=${1:-unified-campaign-review}

# Get AWS region from argument, environment, or use default
AWS_REGION=${2:-${AWS_DEFAULT_REGION:-us-west-2}}

echo "🔍 Getting environment variables from CloudFormation stack: $STACK_NAME"
echo "🌍 Using AWS region: $AWS_REGION"
echo ""

# Check if stack exists
if ! aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION >/dev/null 2>&1; then
    echo "❌ Stack '$STACK_NAME' not found in region $AWS_REGION!"
    echo ""
    echo "Please deploy the stack first:"
    echo "  sam build"
    echo "  sam deploy --stack-name $STACK_NAME --region $AWS_REGION"
    echo ""
    echo "Or specify a different region:"
    echo "  ./setup-env.sh $STACK_NAME us-east-1"
    exit 1
fi

echo "📊 Retrieving stack outputs..."

# Get stack outputs
API_URL=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --region $AWS_REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`ApiEndpoint`].OutputValue' \
    --output text 2>/dev/null)

AGENT_API_URL=$(aws cloudformation describe-stacks \
    --stack-name $STACK_NAME \
    --region $AWS_REGION \
    --query 'Stacks[0].Outputs[?OutputKey==`CampaignOrchestratorApi`].OutputValue' \
    --output text 2>/dev/null)

# Check if we got the values
if [ -z "$API_URL" ]; then
    echo "⚠️  Warning: Could not find ApiEndpoint output"
    API_URL="https://your-http-api-id.execute-api.$AWS_REGION.amazonaws.com"
fi

if [ -z "$AGENT_API_URL" ]; then
    echo "⚠️  Warning: Could not find CampaignOrchestratorApi output"
    AGENT_API_URL="https://your-rest-api-id.execute-api.$AWS_REGION.amazonaws.com/Prod/review-campaign/"
fi

echo ""
echo "✅ Found values:"
echo "   API URL: $API_URL"
echo "   Agent API URL: $AGENT_API_URL"
echo "   Region: $AWS_REGION"
echo ""

# Create .env file
echo "📝 Creating .env file..."

cat > .env << EOF
# Environment variables for Unified Campaign Review System
# Auto-generated by setup-env.sh on $(date)
# Stack: $STACK_NAME
# Region: $AWS_REGION

# HTTP API Gateway endpoint URL (for upload and other frontend functions)
VITE_API_URL=$API_URL

# Campaign Orchestrator API endpoint URL (for agent processing)
VITE_AGENT_API_URL=$AGENT_API_URL

# AWS Region
VITE_AWS_REGION=$AWS_REGION
EOF

echo "✅ .env file created successfully!"
echo ""
echo "📄 Contents:"
cat .env
echo ""
echo "🎯 Next steps:"
echo "   1. Verify the URLs above are correct"
echo "   2. Restart your frontend dev server: npm run dev"
echo "   3. Test the upload functionality"
echo ""
echo "💡 Usage examples:"
echo "   ./setup-env.sh                          # Use defaults"
echo "   ./setup-env.sh genai-campaign-lg        # Custom stack name"
echo "   ./setup-env.sh genai-campaign-lg us-east-1  # Custom stack and region"
echo ""
